#!/usr/bin/env python3
"""
Procedural poetry generator.
A Markov-like / template-based engine generating unique 3-stanza free verse poems.
"""

import random
import textwrap

# ── hardcoded evocative vocabulary bank ──
VOCAB = {
    "nouns": [
        "void", "star", "dust", "noise", "pulse", "glass", "machine",
        "dream", "shard", "echo", "ember", "thread", "orbit", "ghost",
        "static", "silence", "circuit", "mirror", "nebula", "voltage",
        "signal", "entropy", "cipher", "hollow", "prism", "drift",
    ],
    "verbs": [
        "bleeds", "whispers", "shatters", "unravels", "flickers",
        "calcifies", "dissolves", "ignites", "recoils", "listens",
        "oscillates", "collapses", "remembers", "glitches", "devours",
        "haunts", "anchors", "fractures", "hums", "trembles",
    ],
    "adjectives": [
        "ancient", "broken", "electric", "fractal", "hollow",
        "infinite", "lonely", "luminous", "mechanical", "silent",
        "sterile", "tangled", "velvet", "violet", "volatile",
        "wounded", "stellar", "glitched", "crystalline", "spectral",
    ],
    "adverbs": [
        "slowly", "quietly", "forever", "suddenly", "drifting",
        "endlessly", "inward", "softly", "blindly", "mechanically",
    ],
    "prepositions": [
        "through", "beneath", "against", "inside", "beyond",
        "beneath", "within", "amid", "among", "under",
    ],
    "determiners": [
        "the", "a", "this", "every", "no", "all", "that",
    ],
}

PHRASES = [
    "{det} {adj} {noun} {verb}",
    "{noun} {verb} {adv}",
    "{prep} {det} {noun}, {det} {adj} {noun} {verb}",
    "{adj} {noun} {verb} {prep} {det} {noun}",
    "{adv}, {det} {adj} {noun} {verb}",
    "{det} {noun} and {det} {noun} {verb}",
    "{noun}, {noun}, {noun} -- {adv} {verb}",
    "{verb} {prep} {det} {adj} {noun}",
]


def pick(category):
    return random.choice(VOCAB[category])


def make_line():
    template = random.choice(PHRASES)
    try:
        return template.format(
            noun=pick("nouns"),
            verb=pick("verbs"),
            adj=pick("adjectives"),
            adv=pick("adverbs"),
            prep=pick("prepositions"),
            det=pick("determiners"),
        )
    except KeyError:
        # Fallback if template doesn't use all keys (shouldn't happen with current list)
        return f"{pick('adj')} {pick('nouns')} {pick('verbs')}"


def make_stanza(lines=5):
    stanza = []
    for _ in range(lines):
        # Build a line: sometimes simple, sometimes compound.
        line = make_line()
        # Capitalize first letter, strip trailing spaces, add period if absent.
        line = line.strip()
        line = line[0].upper() + line[1:] if line else ""
        if line and line[-1] not in ".,;:!?—":
            line += "."
        stanza.append(line)
    return stanza


def draw_border_block(lines, width=62):
    # Pad / wrap content to fixed width
    box = []
    box.append(" " + "─" * (width + 2) + " ")
    for raw in lines:
        for wrapped in textwrap.wrap(raw, width):
            box.append("│ " + wrapped.ljust(width) + " │")
    box.append(" " + "─" * (width + 2) + " ")
    return box


def main():
    random.seed()  # fresh entropy
    poem_lines = []
    # title
    title = f"{pick('adjectives').title()} {pick('nouns').title()}"
    poem_lines.append(title)
    poem_lines.append("")
    # three stanzas, 4-6 lines each
    for s in range(3):
        stanza = make_stanza(lines=random.randint(4, 6))
        for line in stanza:
            poem_lines.append(line)
        if s < 2:
            poem_lines.append("")  # blank line between stanzas

    # ── assemble with a double ornate border ──
    inner = []
    inner.append("")
    inner.append(" " * 20 + "◈ — POEM — ◈")
    inner.append("")
    for line in poem_lines:
        if line == "":
            inner.append("")
        else:
            inner.append("  " + line)
    inner.append("")
    inner.append(" " * 16 + "— generated by poetry_engine —")
    inner.append("")

    block = draw_border_block(inner, width=58)
    # outer frame
    top =    " ╭" + "═" * 62 + "╮"
    bottom = " ╰" + "═" * 62 + "╯"
    print()
    print(top)
    for bline in block:
        print(" ║" + bline + "║")
    print(bottom)
    print()


if __name__ == "__main__":
    main()
